### ISSUE TITLE
Coop Vault timer is fast.

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#13] opened 2021-05-31 20:45 UTC
**Describe the bug**
When running the vault in coop only mode with multiple players in the vault the timer seems to go really fast

**To Reproduce**
1. Use 1.0.4-streamer1
2. Have multiple players online
3. Enter a vault portal
4. Experience relativity

**Expected behavior**
Vault timer should count down at 1s/s

**Info (please complete the following information):**
- World Type: Server only
- The_Vault Version 1.0.4-Streamer1

**Additional context**
Reported by Lrak--

**Comment by waidesoper** [comment] 2021-06-01 01:02
I've looked at the timer code for this, I can't see what would be causing it. My first thought was that perhaps the timer decrement was occurring once per player (essentially doubling the speed if there are 2 players). Upon further inspection this isn't the case, as it is done on server tick.

**Comment by DDR-Khat** [comment] 2021-06-04 14:30
Is it just perhaps the server falling behind and lagging? As I only observed this rapid ticking in my own testing when players first go into a world, which is naturally more taxing due to world generation.

**Comment by waidesoper** [comment] 2021-06-04 20:20
That sounds more plausible.

**Comment by DDR-Khat** [comment] 2021-06-06 09:52
I can confirm that it is not just lag that is causing it. I suspect your earlier suspicion is correct however; It's ticking down the clock for each player on server tick. So ticks & sTicks -= 1*vaulters

**Comment by DDR-Khat** [comment] 2021-06-07 18:30
Can confirm this was in fact the problem. And resolved by not having the player's tick handle the ticking of the raid instance.

**Closed** 2021-06-07 23:44 UTC
Labels: bug
